version: '3.3'
services:
  ui:  
      container_name: customer-ui
      build: 
        context: customer-web      
      image: angular
      depends_on:
         - api
      ports: 
         - 4200:4200
      expose:
         - 4200
      links:
         - api:api
      command: > 
        bash -c "ng serve --host 0.0.0.0 --port 4200"
        
  api:
   container_name: customer-api 
   build:
     context: customer-api
   image: customer-api
   ports:
      - 9090:9090    
   expose:
      - 9090
   depends_on:
      - db
   links:
      - db:db
      
  db:
    container_name: customer-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: customerdb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: adminpwd
    ports:
      - 3306:3306
    expose:
      - 3306
